/* Plugin Template generated by Pawn Studio */
#include <sourcemod>
#include <clientprefs>

new IMPULS_FLASHLIGHT 						= 100;
new Float:PressTime[MAXPLAYERS+1];

new Handle:db = INVALID_HANDLE;
new ClientPoints[MAXPLAYERS + 1];
 
new Mode; 
new bool:EnableSuvivor; 
new Handle:l4d_nt_team;

public Plugin:myinfo = 
{
	name = "Night Vision",
	author = "Pan Xiaohai & Mr. Zero",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	ConnectDB();
	
	RegConsoleCmd("sm_nightvision", sm_nightvision);
	l4d_nt_team = CreateConVar("l4d_nt_team", "2", " 0:disable, 1:disable, 2:enable for survivor ", FCVAR_PLUGIN);	
	AutoExecConfig(true, "l4d_nightvision"); 
	HookConVarChange(l4d_nt_team, ConVarChange);
	GetConVar();
}

StatsDisabled()
{
	if (db == INVALID_HANDLE) {
		return true;
	}
	return false;
}

public GetClientPoints(Handle:owner, Handle:hndl, const String:error[], any:client)
{
	if (!client || hndl == INVALID_HANDLE) {
		return;
	}

	while (SQL_FetchRow(hndl)) {
		ClientPoints[client] = SQL_FetchInt(hndl, 0);
	}
}

public ConnectDB()
{
	if (SQL_CheckConfig("l4d2stats")) {
		new String:Error[256];
		db = SQL_Connect("l4d2stats", true, Error, sizeof(Error));

		if (db == INVALID_HANDLE) {
			LogError("连接数据库失败,错误: %s", Error);
		}
		else {
			SendSQLUpdate("SET NAMES 'utf8'");
		}
	}
	else {
		LogError("databases.cfg missing 'l4d2stats' entry!");
	}
}

public SendSQLUpdate(String:query[])
{
	if (db == INVALID_HANDLE) {
		return;
	}

	SQL_TQuery(db, SQLErrorCheckCallback, query);
}

public SQLErrorCheckCallback(Handle:owner, Handle:hndl, const String:error[], any:data)
{
	if (db == INVALID_HANDLE) {
		return;
	}

	if(!StrEqual("", error)) {
		LogError("SQL Error: %s", error);
	}
}

public ConVarChange(Handle:convar, const String:oldValue[], const String:newValue[])
{
	GetConVar(); 
}
GetConVar()
{
	Mode=GetConVarInt(l4d_nt_team);
	EnableSuvivor=(Mode==1 || Mode==2);
}
public Action:sm_nightvision(client,args)
{
	if(IsClientInGame(client))SwitchNightVision(client);
}
//code from "Block Flashlight",
public Action:OnPlayerRunCmd(client, &buttons, &impuls, Float:vel[3], Float:angles[3], &weapon)
{
	if(impuls==IMPULS_FLASHLIGHT)
	{		
		new team=GetClientTeam(client);
		if(team==2 && EnableSuvivor)
		{		 	
			new Float:time=GetEngineTime();
			if(time-PressTime[client]<0.3)
			{
				SwitchNightVision(client); 				 
			}
			PressTime[client]=time; 
		}
	}
}
SwitchNightVision(client)
{
	if (StatsDisabled()) {
		return;
	}
	
	decl String:SteamID[30];
	GetClientAuthString(client, SteamID, sizeof(SteamID));
	
	decl String:query[105];
	Format(query, sizeof(query), "SELECT points FROM stats WHERE steamid = '%s'", SteamID); 
	SQL_TQuery(db, GetClientPoints, query, client);
	
	new d=GetEntProp(client, Prop_Send, "m_bNightVisionOn");
	if(ClientPoints[client] >= 500)
	{
		if(d==0 )
		{
			SetEntProp(client, Prop_Send, "m_bNightVisionOn",1); 
			PrintHintText(client, "已开启夜视仪");
		}
		else
		{
			SetEntProp(client, Prop_Send, "m_bNightVisionOn",0);
			PrintHintText(client, "已关闭夜视仪");	
		}
	}
}
